import Head from 'next/head'
import Link from 'next/link'
import {useEffect, useState} from "react";
import ReactPlayer from "react-player";
import FileType from 'file-type/browser'
import styles from '../styles/Home.module.css'
import Post from "../types/Post";
import getCidGatewayUrl from "../util/getCidGatewayUrl";

export default function Home() {

  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {

    (async () => {

      const postsData = await fetch('/api/posts');
      const postJson = await postsData.json()

      setPosts(postJson.posts as Post[])

    })()

  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>


      <Link href="/create">
        <a>Create</a>
      </Link>

      <div>
        {
          posts.map((post) => {
            const source = post.source.type === 'ipfs' ? getCidGatewayUrl(post.source.value) : post.source.value;
            let contentElement = (<a href={source} target='_blank' rel="noreferrer">Content Link</a>)
            if (post.contentType === 'img') {
              contentElement = (<img src={source}/>)
            } else if (post.contentType === 'av') {
              contentElement = (<ReactPlayer url={source} controls/>)
            }


            return (
              <div style={{margin: 40, border: '1px solid black'}} key={post.id}>
                <h3>{post.title}</h3>
                <p>{post.createdAt}</p>
                {
                  contentElement
                }
              </div>
            )
          })
        }
      </div>
    </div>
  )
}
