import Head from 'next/head';
import ProfilePage from '../client/pages/ProfilePage/ProfilePage';

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProfilePage />
    </>
  );
}
