import { Divider, makeStyles, Snackbar } from '@material-ui/core';
import Alert from '@material-ui/lab/Alert';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import ReactPlayer from 'react-player';
import { mutate } from 'swr';
import { GetPostsParams } from '../../../server/types/GetPosts';
import EndpointResult from '../../../types/EndpointResult';
import Post from '../../../types/Post';
import User from '../../../types/User';
import VoteForPost from '../../../types/VoteForPost';
import getCidGatewayUrl from '../../../util/getCidGatewayUrl';
import NavigationBar from '../../components/common/NavigationBar/NavigationBar';
import CreatePostDialog from '../../components/CreatePost/CreatePostDialog';
import CreatePostFab from '../../components/CreatePost/CreatePostFab';
import LoginDialog from '../../components/Login/LoginDialog';
import ImagePostItemContent from '../../components/Posts/PostItem/ImagePostItemContent';
import LinkPostItemContent from '../../components/Posts/PostItem/LinkPostItemContent';
import PostItem from '../../components/Posts/PostItem/PostItem';
import VideoPostItemContent from '../../components/Posts/PostItem/VideoPostItemContent';
import useUser, { GET_USER_SWR_KEY } from '../../hooks/useUser';
import usePosts, { UsePostsVariables } from '../../hooks/usePosts';
import callVoteApi, {
  convertVoteForPostToWeight,
} from '../../util/api/callVoteApi';
import getUserVoteForPost from '../../util/getUserVoteForPost';
import HomePostsContent from './HomePostsContent';
import HomePagePickerBar from './HomePagePickerBar';

const useStyles = makeStyles((theme) => ({}));

export default function HomePage() {
  const classes = useStyles();

  // User
  const { user } = useUser({});

  // Dialogs
  const [showCreatePostDialog, setShowCreatePostDialog] = useState(false);
  const [showLoginDialog, setShowLoginDialog] = useState(false);

  const onCreatePostFabClicked = () => {
    user ? setShowCreatePostDialog(true) : setShowLoginDialog(true);
  };

  // Create post logic
  const [showCreatePostSuccessAlert, setShowCreatePostSuccessAlert] =
    useState(false);
  const closeCreatePostSuccessAlert = () =>
    setShowCreatePostSuccessAlert(false);

  const onPostCreate = (postId: string) => {
    setShowCreatePostDialog(false);
    setShowCreatePostSuccessAlert(true);
  };

  // TODO: loading (maybe have a wrapper?)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Navigation*/}
      <NavigationBar />

      {/*Create Post FAB*/}
      <CreatePostFab onClick={onCreatePostFabClicked} />

      {/*Create Post Dialog*/}
      <CreatePostDialog
        isOpen={showCreatePostDialog}
        setIsOpen={setShowCreatePostDialog}
        onCreate={onPostCreate}
      />
      <Snackbar
        open={showCreatePostSuccessAlert}
        autoHideDuration={5000}
        onClose={closeCreatePostSuccessAlert}
      >
        <Alert onClose={closeCreatePostSuccessAlert} severity="success">
          Your post was published successfully!
        </Alert>
      </Snackbar>

      {/*Login Dialog*/}
      <LoginDialog isOpen={showLoginDialog} setIsOpen={setShowLoginDialog} />

      <HomePostsContent setShowLoginDialog={setShowLoginDialog} />
    </div>
  );
}
