import { makeStyles, Snackbar } from '@material-ui/core';
import Alert from '@material-ui/lab/Alert';
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import ReactPlayer from 'react-player';
import Post from '../../../types/Post';
import VoteForPost from '../../../types/VoteForPost';
import getCidGatewayUrl from '../../../util/getCidGatewayUrl';
import NavigationBar from '../../components/common/NavigationBar/NavigationBar';
import CreatePostDialog from '../../components/CreatePost/CreatePostDialog';
import CreatePostFab from '../../components/CreatePost/CreatePostFab';
import LoginDialog from '../../components/Login/LoginDialog';
import ImagePostItemContent from '../../components/Posts/PostItem/ImagePostItemContent';
import LinkPostItemContent from '../../components/Posts/PostItem/LinkPostItemContent';
import PostItem from '../../components/Posts/PostItem/PostItem';
import VideoPostItemContent from '../../components/Posts/PostItem/VideoPostItemContent';
import useUser from '../../hooks/auth/useUser';
import callVoteApi from '../../util/api/callVoteApi';
import getUserVoteForPost from '../../util/getUserVoteForPost';

const useStyles = makeStyles((theme) => ({}));

export default function HomePage() {
  const classes = useStyles();

  // User
  const { user } = useUser({});

  // Dialogs
  const [showCreatePostDialog, setShowCreatePostDialog] = useState(false);
  const [showLoginDialog, setShowLoginDialog] = useState(false);

  const onCreatePostFabClicked = () => {
    user ? setShowCreatePostDialog(true) : setShowLoginDialog(true);
  };

  // TODO: use Posts
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    (async () => {
      const postsData = await fetch('/api/posts?tallyIndex=0');
      const postJson = await postsData.json();

      setPosts(postJson.data.posts as Post[]);
    })();
  }, []);

  const onLogoutClicked = () => {
    (async () => {
      const resp = await fetch('/api/auth/logout');
      const respJson = await resp.json();
      console.log('Logged out', respJson);
      location.reload();
    })();
  };

  const onVoteClicked = async (postId: string, vote?: VoteForPost) => {
    if (user == null) {
      setShowLoginDialog(true);
      return;
    }

    // TODO update data in usePosts then mutate
    await callVoteApi(postId, vote);
  };

  // Create post logic
  const [showCreatePostSuccessAlert, setShowCreatePostSuccessAlert] =
    useState(false);
  const closeCreatePostSuccessAlert = () =>
    setShowCreatePostSuccessAlert(false);

  const onPostCreate = (postId: string) => {
    console.log('On post create', postId);
    setShowCreatePostDialog(false);
    setShowCreatePostSuccessAlert(true);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Navigation*/}
      <NavigationBar />

      {/*Create Post FAB*/}
      <CreatePostFab onClick={onCreatePostFabClicked} />

      {/*Create Post Dialog*/}
      <CreatePostDialog
        isOpen={showCreatePostDialog}
        setIsOpen={setShowCreatePostDialog}
        onCreate={onPostCreate}
      />
      <Snackbar
        open={showCreatePostSuccessAlert}
        autoHideDuration={5000}
        onClose={closeCreatePostSuccessAlert}
      >
        <Alert onClose={closeCreatePostSuccessAlert} severity="success">
          Your post was published successfully!
        </Alert>
      </Snackbar>

      {/*Login Dialog*/}
      <LoginDialog isOpen={showLoginDialog} setIsOpen={setShowLoginDialog} />

      {/*Scrap*/}
      <div>
        {user && (
          <div>
            <p>Current user:</p>
            <pre>{JSON.stringify(user, null, 2)}</pre>
            <button onClick={onLogoutClicked}>Log Out</button>
          </div>
        )}
      </div>

      <div>
        {posts.map((post) => {
          return (
            <div style={{ margin: 12 }}>
              <PostItem
                post={post}
                key={post.id}
                onVoteClicked={onVoteClicked}
                currentUserVote={
                  user ? getUserVoteForPost(post, user) : undefined
                }
              />
            </div>
          );
        })}
      </div>
    </div>
  );
}
