name: daily-tally-cron
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call Tally API
        run: |
          curl --location --request POST 'https://tuno.vercel.app//api/tally' \
          --header 'Authorization: ${{ secrets.TALLY_SECRET_KEY }}'
